version: '3.8'

services:
  db_my_app_dinheiro:
    build:
      context: .
      dockerfile: ./banco/postgres/Dockerfile
    container_name: db_my_app_dinheiro
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./flyway/sql:/flyway/sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
